spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FOA_DB
    username: root
    password: Harish@1606
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

server:
  port: 8183
  error:
    include-message: always