spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
          - Path=/authentication/**
          filters:
            - name: CircuitBreaker
              args:
                name: authentication-service
                fallbackuri: forward:/authenticationFallback

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallback

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
